version: '3'
services:
 nginx:
   image: nginx:1
   container_name: nginx_parsing
   volumes:
    - ./www:/usr/share/nginx/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
    - php
   ports:
    - "80"
 php:
   image: php:fpm
   command: /bin/sh /var/www/start.sh
   volumes:
    - ./start.sh:/var/www/start.sh
    - ./www:/var/www/html
    - ./php-fpm/www-2.conf:/usr/local/etc/php-fpm.d/www-2.conf