version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: antswordproject/antsword-labs:bypass_disable_functions_3
    container_name: disable_functions_2
    ports:
      - "80"
