version: '3'
services:
 web:
   image: vulhub/joomla:3.4.5
   container_name: CVE-2015-8562
   depends_on:
    - mysql
   environment: 
    - JOOMLA_DB_HOST=mysql:3306
    - JOOMLA_DB_USER=root
    - JOOMLA_DB_PASSWORD=root
    - JOOMLA_DB_NAME=joomla
   ports:
    - "80"
 mysql:
   image: mysql:5
   environment: 
    - MYSQL_ROOT_PASSWORD=root
