version: '3'
services:
 nginx:
   image: vulhub/nginx:1.4.2
   container_name: CVE-2013-4547
   volumes:
    - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    - ./www:/usr/local/nginx/html
   ports:
    - "80"
 php:
   build: ./php-fpm/
   volumes:
    - ./www:/var/www/html