version: '3'
services:
 web:
   depends_on:
    - db-level-unauthorized
   environment: 
    - DB_HOST=db:3306
   build: .
   container_name: level_unauthorized
   volumes:
    - ./www:/var/www/html
   ports:
    - "80"
 db-level-unauthorized:
   image: mysql:5.7.26
   container_name: mysql-level-unauthorized
   command:
    --default_authentication_plugin=mysql_native_password
    --character-set-server=utf8mb4
    --collation-server=utf8mb4_unicode_ci
   volumes:
    - ./www/db:/var/lib/mysql
    - ./www/init:/docker-entrypoint-initdb.d/
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: level-unauthorized
